export const menus = [
  {
    id: 1,
    img: "/src/assets/bg.jpg",
    name: "Sexy  Burger",
    description:
      "Juicy beef patty with lettuce, tomato, and special sauce and extra cheese",
    regularPrice: 15.99,
    mediumPrice: 10.99,
    calories: 650,
  },
  {
    id: 2,
    img: "/src/assets/bb11.jpeg",
    name: "bhjb  ",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    regularPrice: 12.99,
    mediumPrice: 10.99,
    calories: 650,
  },
  {
    id: 3,
    img: "/src/assets/bg.jpg",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    regularPrice: 12.99,
    mediumPrice: 10.99,
    calories: 650,
  },
  {
    id: 4,
    img: "/src/assets/bg.jpg",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    regularPrice: 12.99,
    mediumPrice: 10.99,
    calories: 650,
  },
  {
    id: 5,
    img: "/src/assets/bg.jpg",
    name: "Sexy  Burger",
    description:
      "Juicy beef patty with lettuce, tomato, and special sauce and extra cheese",
    regularPrice: 15.99,
    mediumPrice: 10.99,
    calories: 650,
  },
  {
    id: 6,
    img: "/src/assets/bb11.jpeg",
    name: "bhjb  ",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    regularPrice: 12.99,
    mediumPrice: 10.99,
    calories: 650,
  },
  {
    id: 7,
    img: "/src/assets/bg.jpg",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    regularPrice: 12.99,
    mediumPrice: 10.99,
    calories: 650,
  },
  {
    id: 8,
    img: "/src/assets/bg.jpg",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    regularPrice: 12.99,
    mediumPrice: 10.99,
    calories: 650,
  },
];

export const sandwiches = [
  {
    id: 1,
    img: "/src/assets/bg1.jpg",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    regularPrice: 12.99,
    mediumPrice: 10.99,
    calories: 650,
  },
  {
    id: 1,
    img: "/src/assets/bg.jpg",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    regularPrice: 12.99,
    mediumPrice: 10.99,
    calories: 650,
  },
  {
    id: 1,
    img: "/src/assets/bg.jpg",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    regularPrice: 12.99,
    mediumPrice: 10.99,
    calories: 650,
  },
  {
    id: 1,
    img: "/src/assets/bg.jpg",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    regularPrice: 12.99,
    mediumPrice: 10.99,
    calories: 650,
  },
  {
    id: 1,
    img: "/src/assets/bg.jpg",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    regularPrice: 12.99,
    mediumPrice: 10.99,
    calories: 650,
  },
]
  export const Chickens = [
    {
      id: 1,
      img: "/src/assets/g1.jpg",
      name: "Classic Burger",
      description: "Juicy beef patty with lettuce, tomato, and special sauce",
      regularPrice: 12.99,
      mediumPrice: 10.99,
      calories: 650,
    },
    {
      id: 1,
      img: "/src/assets/bg.jpg",
      name: "Classic Burger",
      description: "Juicy beef patty with lettuce, tomato, and special sauce",
      regularPrice: 12.99,
      mediumPrice: 10.99,
      calories: 650,
    },
    {
      id: 1,
      img: "/src/assets/bg.jpg",
      name: "Classic Burger",
      description: "Juicy beef patty with lettuce, tomato, and special sauce",
      regularPrice: 12.99,
      mediumPrice: 10.99,
      calories: 650,
    },
    {
      id: 1,
      img: "/src/assets/bg.jpg",
      name: "Classic Burger",
      description: "Juicy beef patty with lettuce, tomato, and special sauce",
      regularPrice: 12.99,
      mediumPrice: 10.99,
      calories: 650,
    },
    {
      id: 1,
      img: "/src/assets/bg.jpg",
      name: "Classic Burger",
      description: "Juicy beef patty with lettuce, tomato, and special sauce",
      regularPrice: 12.99,
      mediumPrice: 10.99,
      calories: 650,
    },
];
export const Rice = [
  {
    id: 1,
    img: "/src/assets/g1.jpg",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    regularPrice: 12.99,
    mediumPrice: 10.99,
    calories: 650,
  },
  {
    id: 1,
    img: "/src/assets/bg.jpg",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    regularPrice: 12.99,
    mediumPrice: 10.99,
    calories: 650,
  },
  {
    id: 1,
    img: "/src/assets/bg.jpg",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    regularPrice: 12.99,
    mediumPrice: 10.99,
    calories: 650,
  },
  {
    id: 1,
    img: "/src/assets/bg.jpg",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    regularPrice: 12.99,
    mediumPrice: 10.99,
    calories: 650,
  },
  {
    id: 1,
    img: "/src/assets/bg.jpg",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    regularPrice: 12.99,
    mediumPrice: 10.99,
    calories: 650,
  },
];
export const Shakes = [
  {
    id: 1,
    img: "/src/assets/gg.jpg",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    regularPrice: 12.99,
    mediumPrice: 10.99,
    calories: 650,
  },
  {
    id: 1,
    img: "/src/assets/bg.jpg",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    regularPrice: 12.99,
    mediumPrice: 10.99,
    calories: 650,
  },
  {
    id: 1,
    img: "/src/assets/bg.jpg",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    regularPrice: 12.99,
    mediumPrice: 10.99,
    calories: 650,
  },
  {
    id: 1,
    img: "/src/assets/bg.jpg",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    regularPrice: 12.99,
    mediumPrice: 10.99,
    calories: 650,
  },
  {
    id: 1,
    img: "/src/assets/bg.jpg",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    regularPrice: 12.99,
    mediumPrice: 10.99,
    calories: 650,
  },
];
export const Potatoes = [
  {
    id: 1,
    img: "/src/assets/gg.jpg",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    regularPrice: 12.99,
    mediumPrice: 10.99,
    calories: 650,
  },
  {
    id: 1,
    img: "/src/assets/bg.jpg",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    regularPrice: 12.99,
    mediumPrice: 10.99,
    calories: 650,
  },
  {
    id: 1,
    img: "/src/assets/bg.jpg",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    regularPrice: 12.99,
    mediumPrice: 10.99,
    calories: 650,
  },
  {
    id: 1,
    img: "/src/assets/bg.jpg",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    regularPrice: 12.99,
    mediumPrice: 10.99,
    calories: 650,
  },
  {
    id: 1,
    img: "/src/assets/bg.jpg",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    regularPrice: 12.99,
    mediumPrice: 10.99,
    calories: 650,
  },
];
export const SweetTooth = [
  {
    id: 1,
    img: "/src/assets/bg1.jpg",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    regularPrice: 12.99,
    mediumPrice: 10.99,
    calories: 650,
  },
  {
    id: 1,
    img: "/src/assets/bg.jpg",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    regularPrice: 12.99,
    mediumPrice: 10.99,
    calories: 650,
  },
  {
    id: 1,
    img: "/src/assets/bg.jpg",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    regularPrice: 12.99,
    mediumPrice: 10.99,
    calories: 650,
  },
  {
    id: 1,
    img: "/src/assets/bg.jpg",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    regularPrice: 12.99,
    mediumPrice: 10.99,
    calories: 650,
  },
  {
    id: 1,
    img: "/src/assets/bg.jpg",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    regularPrice: 12.99,
    mediumPrice: 10.99,
    calories: 650,
  },
];
